Main svc
pnikishechkin/java-explore-with-me pull request #2
Opened 2024-12-04 13:46 UTC by pnikishechkin

2024-12-05 09:20 UTC, tomattman requested changes
Привет, вроде все хорошо, но есть всякие мелочи на исправление

2024-12-05 09:20 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/MainService.java
> +        //ConfigurableApplicationContext context =
закоментированный код не допускается

2024-12-05 09:20 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/category/CategoryRepository.java
> +    List<Category> findAllLimitOffset(Integer offset, Integer limit);
для пагинации можно сделать все проще
обычный запрос но в параметрах Pageable 
List<Category> findAll(Pageable pageable);

2024-12-05 09:20 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/category/CategoryServiceImpl.java
> +        // return categoryRepository.findAll(PageRequest.of(from, size)).stream().toList();
закоментированный код

2024-12-05 09:20 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/compilation/CompilationRepository.java
> +    List<Compilation> findByFromSize(Integer from, Integer size);
аналогично как с категориями

2024-12-05 09:20 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/compilation/CompilationControllerAdmin.java
> +    public CompilationDto postCompilation(@RequestBody @Validated NewCompilationDto newCompilationDto) {
плохое название метода
лучше назвать createCompilation

2024-12-05 09:20 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/compilation/CompilationControllerAdmin.java
> +    public CompilationDto patchCompilation(@PathVariable Long compId,
И снова про имя, почему бы не назвать update

2024-12-05 09:20 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/compilation/CompilationServiceImpl.java
> +    public CompilationDto post(NewCompilationDto newCompilationDto) {
И тут то же самое по именам

2024-12-05 09:20 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/event/EventControllerAdmin.java
> +    public EventFullDto patchEvent(@PathVariable Long eventId,
снова по именам, больше писать не буду

2024-12-05 09:20 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/event/Event.java
> +package ru.practicum.ewm.main.event;
Очень много классов в одном пакете , можно было бы разделить по пакетам дополнительно

2024-12-05 16:42 UTC, pnikishechkin commented on main-service/src/main/java/ru/practicum/ewm/main/category/CategoryRepository.java
> +    List<Category> findAllLimitOffset(Integer offset, Integer limit);
Насколько я понял, Pageable удобно использовать, когда надо сделать постраничный вывод.
Но у нас по заданию надо: "количество **элементов**, которые нужно пропустить для формирования текущего набора", то есть это смещение именно по элементам, а не по странице. Ну или сделать кастомную реализацию, где это самое смещение рассчитывать. Для фичи попробую этот вариант.
Но использование OFFSET и LIMIT в запросе же допустимо?

2024-12-06 11:00 UTC, tomattman commented on main-service/src/main/java/ru/practicum/ewm/main/category/CategoryRepository.java
> +    List<Category> findAllLimitOffset(Integer offset, Integer limit);
Пагинация по сути представляет собой как раз таки пропуск определенного количества результатов для формирования текущего набора элементов и работает она как раз таки через offset И limit для формирования этой самой страницы
Просто JPQL запросы не поддерживают такие операции как limit и используя пагинацию можно получить те же данные 
Использование конечно допустимо и тут идет зависимость уже от того как принято на проекте, где то все запросы строятся на nativeQuery а где то стараются их избегать по максимуму

2024-12-06 11:00 UTC, tomattman approved these changes
Принято

2024-12-06 11:22 UTC, merged